export const CURRENCIES = {
  AED: { symbol: 'د.إ', name: 'UAE Dirham', position: 'before' },
  AFN: { symbol: 'Af', name: 'Afghan Afghani', position: 'before' },
  ALL: { symbol: 'L', name: 'Albanian Lek', position: 'before' },
  AMD: { symbol: '֏', name: 'Armenian Dram', position: 'before' },
  ANG: { symbol: 'ƒ', name: 'Dutch Guilder', position: 'before' },
  AOA: { symbol: 'Kz', name: 'Angolan Kwanza', position: 'before' },
  ARS: { symbol: '$', name: 'Argentine Peso', position: 'before' },
  AUD: { symbol: 'A$', name: 'Australian Dollar', position: 'before' },
  AWG: { symbol: 'ƒ', name: 'Aruban Guilder', position: 'before' },
  AZN: { symbol: '₼', name: 'Azerbaijan Manat', position: 'before' },
  BAM: { symbol: 'KM', name: 'Bosnian Convertible Mark', position: 'before' },
  BBD: { symbol: '$', name: 'Barbadian Dollar', position: 'before' },
  BDT: { symbol: '৳', name: 'Bangladeshi Taka', position: 'before' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', position: 'before' },
  BHD: { symbol: '.د.ب', name: 'Bahraini Dinar', position: 'before' },
  BIF: { symbol: 'Fr', name: 'Burundian Franc', position: 'before' },
  BMD: { symbol: '$', name: 'Bermudian Dollar', position: 'before' },
  BND: { symbol: '$', name: 'Bruneian Dollar', position: 'before' },
  BOB: { symbol: 'Bs', name: 'Bolivian Bolíviano', position: 'before' },
  BRL: { symbol: 'R$', name: 'Brazilian Real', position: 'before' },
  BSD: { symbol: '$', name: 'Bahamian Dollar', position: 'before' },
  BTN: { symbol: 'Nu.', name: 'Bhutanese Ngultrum', position: 'before' },
  BWP: { symbol: 'P', name: 'Botswana Pula', position: 'before' },
  BYN: { symbol: 'Br', name: 'Belarusian Ruble', position: 'before' },
  BZD: { symbol: '$', name: 'Belizean Dollar', position: 'before' },
  CAD: { symbol: 'C$', name: 'Canadian Dollar', position: 'before' },
  CDF: { symbol: 'Fr', name: 'Congolese Franc', position: 'before' },
  CHF: { symbol: 'CHF', name: 'Swiss Franc', position: 'before' },
  CLP: { symbol: '$', name: 'Chilean Peso', position: 'before' },
  CNY: { symbol: '¥', name: 'Chinese Yuan', position: 'before' },
  COP: { symbol: '$', name: 'Colombian Peso', position: 'before' },
  CRC: { symbol: '₡', name: 'Costa Rican Colon', position: 'before' },
  CUP: { symbol: '$', name: 'Cuban Peso', position: 'before' },
  CVE: { symbol: '$', name: 'Cape Verdean Escudo', position: 'before' },
  CZK: { symbol: 'Kč', name: 'Czech Koruna', position: 'after' },
  DJF: { symbol: 'Fr', name: 'Djiboutian Franc', position: 'before' },
  DKK: { symbol: 'kr', name: 'Danish Krone', position: 'before' },
  DOP: { symbol: '$', name: 'Dominican Peso', position: 'before' },
  DZD: { symbol: 'د.ج', name: 'Algerian Dinar', position: 'before' },
  EGP: { symbol: 'E£', name: 'Egyptian Pound', position: 'before' },
  ERN: { symbol: 'Nfk', name: 'Eritrean Nakfa', position: 'before' },
  ETB: { symbol: 'Br', name: 'Ethiopian Birr', position: 'before' },
  EUR: { symbol: '€', name: 'Euro', position: 'before' },
  FJD: { symbol: '$', name: 'Fijian Dollar', position: 'before' },
  FKP: { symbol: '£', name: 'Falkland Island Pound', position: 'before' },
  GBP: { symbol: '£', name: 'British Pound', position: 'before' },
  GEL: { symbol: '₾', name: 'Georgian Lari', position: 'before' },
  GHS: { symbol: '₵', name: 'Ghanaian Cedi', position: 'before' },
  GIP: { symbol: '£', name: 'Gibraltar Pound', position: 'before' },
  GMD: { symbol: 'D', name: 'Gambian Dalasi', position: 'before' },
  GNF: { symbol: 'Fr', name: 'Guinean Franc', position: 'before' },
  GTQ: { symbol: 'Q', name: 'Guatemalan Quetzal', position: 'before' },
  GYD: { symbol: '$', name: 'Guyanese Dollar', position: 'before' },
  HKD: { symbol: 'HK$', name: 'Hong Kong Dollar', position: 'before' },
  HNL: { symbol: 'L', name: 'Honduran Lempira', position: 'before' },
  HRK: { symbol: 'kn', name: 'Croatian Kuna', position: 'before' },
  HTG: { symbol: 'G', name: 'Haitian Gourde', position: 'before' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint', position: 'before' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah', position: 'before' },
  ILS: { symbol: '₪', name: 'Israeli Shekel', position: 'before' },
  INR: { symbol: '₹', name: 'Indian Rupee', position: 'before' },
  IQD: { symbol: 'ع.د', name: 'Iraqi Dinar', position: 'before' },
  IRR: { symbol: '﷼', name: 'Iranian Rial', position: 'before' },
  ISK: { symbol: 'kr', name: 'Icelandic Krona', position: 'before' },
  JMD: { symbol: '$', name: 'Jamaican Dollar', position: 'before' },
  JOD: { symbol: 'د.ا', name: 'Jordanian Dinar', position: 'before' },
  JPY: { symbol: '¥', name: 'Japanese Yen', position: 'before' },
  KES: { symbol: 'KSh', name: 'Kenyan Shilling', position: 'before' },
  KGS: { symbol: 'сом', name: 'Kyrgyzstani Som', position: 'before' },
  KHR: { symbol: '៛', name: 'Cambodian Riel', position: 'before' },
  KMF: { symbol: 'Fr', name: 'Comorian Franc', position: 'before' },
  KPW: { symbol: '₩', name: 'North Korean Won', position: 'before' },
  KRW: { symbol: '₩', name: 'South Korean Won', position: 'before' },
  KWD: { symbol: 'د.ك', name: 'Kuwaiti Dinar', position: 'before' },
  KYD: { symbol: '$', name: 'Caymanian Dollar', position: 'before' },
  KZT: { symbol: '₸', name: 'Kazakhstani Tenge', position: 'before' },
  LAK: { symbol: '₭', name: 'Lao Kip', position: 'before' },
  LBP: { symbol: 'ل.ل', name: 'Lebanese Pound', position: 'before' },
  LKR: { symbol: 'Rs', name: 'Sri Lankan Rupee', position: 'before' },
  LRD: { symbol: '$', name: 'Liberian Dollar', position: 'before' },
  LSL: { symbol: 'L', name: 'Basotho Loti', position: 'before' },
  LYD: { symbol: 'ل.د', name: 'Libyan Dinar', position: 'before' },
  MAD: { symbol: 'د.م.', name: 'Moroccan Dirham', position: 'before' },
  MDL: { symbol: 'L', name: 'Moldovan Leu', position: 'before' },
  MGA: { symbol: 'Ar', name: 'Malagasy Ariary', position: 'before' },
  MKD: { symbol: 'ден', name: 'Macedonian Denar', position: 'before' },
  MMK: { symbol: 'K', name: 'Burmese Kyat', position: 'before' },
  MNT: { symbol: '₮', name: 'Mongolian Tughrik', position: 'before' },
  MOP: { symbol: 'P', name: 'Macau Pataca', position: 'before' },
  MRU: { symbol: 'UM', name: 'Mauritanian Ouguiya', position: 'before' },
  MUR: { symbol: 'Rs', name: 'Mauritian Rupee', position: 'before' },
  MVR: { symbol: '.MRf', name: 'Maldivian Rufiyaa', position: 'before' },
  MWK: { symbol: 'MK', name: 'Malawian Kwacha', position: 'before' },
  MXN: { symbol: '$', name: 'Mexican Peso', position: 'before' },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit', position: 'before' },
  MZN: { symbol: 'MT', name: 'Mozambican Metical', position: 'before' },
  NAD: { symbol: '$', name: 'Namibian Dollar', position: 'before' },
  NGN: { symbol: '₦', name: 'Nigerian Naira', position: 'before' },
  NIO: { symbol: 'C$', name: 'Nicaraguan Cordoba', position: 'before' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone', position: 'before' },
  NPR: { symbol: 'Rs', name: 'Nepalese Rupee', position: 'before' },
  NZD: { symbol: 'NZ$', name: 'New Zealand Dollar', position: 'before' },
  OMR: { symbol: 'ر.ع.', name: 'Omani Rial', position: 'before' },
  PAB: { symbol: 'B/.', name: 'Panamanian Balboa', position: 'before' },
  PEN: { symbol: 'S/', name: 'Peruvian Sol', position: 'before' },
  PGK: { symbol: 'K', name: 'Papua New Guinean Kina', position: 'before' },
  PHP: { symbol: '₱', name: 'Philippine Peso', position: 'before' },
  PKR: { symbol: '₨', name: 'Pakistani Rupee', position: 'before' },
  PLN: { symbol: 'zł', name: 'Polish Zloty', position: 'after' },
  PYG: { symbol: '₲', name: 'Paraguayan Guarani', position: 'before' },
  QAR: { symbol: 'ر.ق', name: 'Qatari Riyal', position: 'before' },
  RON: { symbol: 'lei', name: 'Romanian Leu', position: 'before' },
  RSD: { symbol: 'дин.', name: 'Serbian Dinar', position: 'before' },
  RUB: { symbol: '₽', name: 'Russian Ruble', position: 'before' },
  RWF: { symbol: 'Fr', name: 'Rwandan Franc', position: 'before' },
  SAR: { symbol: 'ر.س', name: 'Saudi Riyal', position: 'before' },
  SBD: { symbol: '$', name: 'Solomon Islander Dollar', position: 'before' },
  SCR: { symbol: 'Rs', name: 'Seychellois Rupee', position: 'before' },
  SDG: { symbol: 'ج.س.', name: 'Sudanese Pound', position: 'before' },
  SEK: { symbol: 'kr', name: 'Swedish Krona', position: 'before' },
  SGD: { symbol: 'S$', name: 'Singapore Dollar', position: 'before' },
  SHP: { symbol: '£', name: 'Saint Helenian Pound', position: 'before' },
  SLE: { symbol: 'Le', name: 'Sierra Leonean Leone', position: 'before' },
  SLL: { symbol: 'Le', name: 'Sierra Leonean Leone', position: 'before' },
  SOS: { symbol: 'Sh', name: 'Somali Shilling', position: 'before' },
  SRD: { symbol: '$', name: 'Surinamese Dollar', position: 'before' },
  SSP: { symbol: '£', name: 'South Sudanese Pound', position: 'before' },
  STD: { symbol: 'Db', name: 'Sao Tomean Dobra', position: 'before' },
  STN: { symbol: 'Db', name: 'Sao Tomean Dobra', position: 'before' },
  SYP: { symbol: '£', name: 'Syrian Pound', position: 'before' },
  SZL: { symbol: 'E', name: 'Swazi Lilangeni', position: 'before' },
  THB: { symbol: '฿', name: 'Thai Baht', position: 'before' },
  TJS: { symbol: 'SM', name: 'Tajikistani Somoni', position: 'before' },
  TMT: { symbol: 'm', name: 'Turkmenistani Manat', position: 'before' },
  TND: { symbol: 'د.ت', name: 'Tunisian Dinar', position: 'before' },
  TOP: { symbol: 'T$', name: 'Tongan Pa\'anga', position: 'before' },
  TRY: { symbol: '₺', name: 'Turkish Lira', position: 'before' },
  TTD: { symbol: '$', name: 'Trinidadian Dollar', position: 'before' },
  TWD: { symbol: '$', name: 'Taiwan Dollar', position: 'before' },
  TZS: { symbol: 'Sh', name: 'Tanzanian Shilling', position: 'before' },
  UAH: { symbol: '₴', name: 'Ukrainian Hryvnia', position: 'before' },
  UGX: { symbol: 'USh', name: 'Ugandan Shilling', position: 'before' },
  USD: { symbol: '$', name: 'US Dollar', position: 'before' },
  UYU: { symbol: '$', name: 'Uruguayan Peso', position: 'before' },
  UZS: { symbol: 'som', name: 'Uzbekistani Som', position: 'before' },
  VES: { symbol: 'Bs.S', name: 'Venezuelan Bolívar', position: 'before' },
  VND: { symbol: '₫', name: 'Vietnamese Dong', position: 'before' },
  VUV: { symbol: 'VT', name: 'Ni-Vanuatu Vatu', position: 'before' },
  WST: { symbol: 'T', name: 'Samoan Tala', position: 'before' },
  XAF: { symbol: 'Fr', name: 'Central African CFA Franc', position: 'before' },
  XCD: { symbol: '$', name: 'East Caribbean Dollar', position: 'before' },
  XDR: { symbol: 'SDR', name: 'IMF Special Drawing Rights', position: 'before' },
  XOF: { symbol: 'Fr', name: 'CFA Franc', position: 'before' },
  XPF: { symbol: 'Fr', name: 'CFP Franc', position: 'before' },
  YER: { symbol: '﷼', name: 'Yemeni Rial', position: 'before' },
  ZAR: { symbol: 'R', name: 'South African Rand', position: 'before' },
  ZMW: { symbol: 'ZK', name: 'Zambian Kwacha', position: 'before' },
  ZWL: { symbol: '$', name: 'Zimbabwean Dollar', position: 'before' }
};

export const SYMBOL_TO_CURRENCY = {
  '$': 'USD',
  '€': 'EUR',
  '£': 'GBP',
  '¥': 'JPY',
  '₹': 'INR',
  '₽': 'RUB',
  '₩': 'KRW',
  '₺': 'TRY',
  '฿': 'THB',
  '₱': 'PHP',
  '₪': 'ILS',
  '৳': 'BDT',
  '₨': 'PKR',
  '₸': 'KZT',
  '₮': 'MNT',
  '₭': 'LAK',
  '₾': 'GEL',
  '₦': 'NGN',
  '₲': 'PYG',
  '₴': 'UAH',
  '₫': 'VND',
  '₡': 'CRC',
  '₢': 'BRL',
  '₣': 'CHF',
  '₤': 'GBP',
  '₥': 'USD',
  '₦': 'NGN',
  '₧': 'ESP',
  '₨': 'PKR',
  '₪': 'ILS',
  '₫': 'VND',
  '€': 'EUR',
  '﷼': 'IRR',
  '৳': 'BDT',
  '฿': 'THB',
  '₵': 'GHS',
  '₭': 'LAK',
  '₮': 'MNT',
  '₯': 'GRD',
  'Ᵽ': 'PKR',
  '₠': 'EUR',
  '₡': 'CRC',
  '₢': 'BRL',
  '₣': 'CHF',
  '₤': 'GBP',
  '₥': 'USD',
  '₦': 'NGN',
  '₧': 'ESP',
  '₨': 'PKR',
  '₪': 'ILS',
  '₫': 'VND',
  '€': 'EUR',
  '₭': 'LAK',
  '₮': 'MNT',
  '₯': 'GRD',
  '⃀': 'ZAR'
};

export const CODE_PATTERN = Object.keys(CURRENCIES).join('|');
